### ISSUE TITLE
ESCs not detecting on configurator when uploaded bluejay firmware using the C2 interface for EFM8BB21

### ISSUE THREAD

**Issue by JustCurious8** [bird-sanctuary/arduino-bi-directional-dshot#2]
I have flashed this arduino code on arduino Uno, pulled digital pin 13 low to enable C2 interface to upload the firmware on EFM8BB21 mcu using the python EFM8 client. All the steps and actions of reading, writing and erasing the firmware from flash memory seemed to worked using the python EFM8 client. But the issue is Bluejay ESC configurator is not able to detect the ESCs and also when connecting individual EFM8BB21 microcontroller on blhelisuite using C2 interface then it is not showing the bluejay firmware.

Below i am explaining all the steps with images and different observations which i have found with above mentioned issue :

**1)** This is my starting point and i am using mamba 4 in 1 ESCs and uploaded bluejay firmware on 2 BB2 mcu and blheli_S on 1 BB2 mcu using blhelisuite and their C2 interface implementation, ignore the 4th mcu as it is having some issue with detection using blheli passthrough.  You can see how all three MCUs are getting detected both in blhelisuite and bluejay esc configurator.
![Screenshot (2)](https://user-images.githubusercontent.com/25478862/205066605-49e9cfd7-7905-4104-a935-afe4f1db47e0.png)
![Screenshot (3)](https://user-images.githubusercontent.com/25478862/205067120-9686bd32-e6d0-4c01-bc70-4aea3aef2461.png)

  
**2)** Next, i am going to replace the firmware of 3rd MCU from blheli_S to bluejay firmware using this arduino code and python EFM8 client. In this step i am running just the `pipenv install and shell` commands in terminal.
![1](https://user-images.githubusercontent.com/25478862/205068788-ca37a942-f24d-40e5-9ce0-a36ebca2439a.png)

**3)** At first, i am reading blheli_S firmware in a hex file using `python efm8.py read`. Hex file is attached below inside the google drive folder by name `1_read_blheli_S.hex`

![2](https://user-images.githubusercontent.com/25478862/205071464-24aebac2-c258-4dd4-a94a-1b904123dd8b.png)

**4)** Next, i am just erasing the flash memory using `python efm8.py erase`. After erasing i am reading the flash memory again using `python efm8.py read` and saving the file by name `2_read_after_erase.hex` attached in the google drive folder.
![3](https://user-images.githubusercontent.com/25478862/205073184-a4cc7088-046a-4261-b9d9-f538cea78345.png)

 
![4](https://user-images.githubusercontent.com/25478862/205073201-934c7a4d-5e1b-4efc-b68a-237b1650c9ab.png)

**5)** In last step, i am just writing the bluejay firmware using `python efm8.py write` and also read the flash memory again to retrieve the hex file by name `3_read_bluejay.hex` and attached the file in google drive folder. 
![5](https://user-images.githubusercontent.com/25478862/205074666-8fb3d8ec-b42d-4c08-91f4-0b89bc3b660c.png)
![6](https://user-images.githubusercontent.com/25478862/205074694-da44c2bc-12d6-446f-97c6-f1e220c9a993.png)

![7](https://user-images.githubusercontent.com/25478862/205074719-7e5c0999-415d-4ac2-8215-36e8bc6a7acc.png)

**6)** Finally, when i connected the FC and ESC and then connected to bluejay esc configurator and blhelisuite using blheli passthrough then this is the ouput.
![Screenshot (4)](https://user-images.githubusercontent.com/25478862/205075597-f5c015e8-63ae-4ac2-984d-6eae2870dfd7.png)
![Screenshot (5)](https://user-images.githubusercontent.com/25478862/205075620-e8dda87b-3215-4593-afd7-7d1b6109fce4.png)

**7)** At last when i connected that particular BB2 mcu using C2 Interface with blhelisuite then firmware name showing up as older blheli firmware only which was running before and not the bluejay firmware which uploaded using python EFM8 client. 
![Screenshot (6)](https://user-images.githubusercontent.com/25478862/205077956-bd4b49cf-20d7-45d3-9717-bcb4013521bd.png)

Google drive folder : https://drive.google.com/drive/folders/1eVz0XD52Igj79Hf7zNCxDW-Xv9ZMmg18?usp=sharing
Also attached the blheli_S firmware which was running before and also the bluejay firmware which uploaded using the python EFM8 client in the above google drive folder.

So these are all the results and observations. I am not able to decode what is going wrong here. Please do let me know if some other data is required to decode the underlying issue here. Please do suggest anything which i can try and upload bluejay firmware using this arduino code and python EFM8 client.

**Comment by JustCurious8** [comment]
Another problem i have found is with EFM8BB21 that read operation is not working properly. I have uploaded this bluejay firmware https://github.com/bird-sanctuary/bluejay/releases/download/v0.16/A_H_40_48_v0.16.hex on one EFM8BB21 MCU from blhelisuite. But when reading the flash data back from python EFM8 client using `python efm8.py read` , this is the hex file which generated https://drive.google.com/file/d/1b0g39F9PMAzMRPtRvjswmE-f3ClJd0qy/view?usp=sharing

Hex data after reading is like that:
:100000000219fd020360ff03030303030303030359
:100010000219fd020360ff03030303030303030349
:100020000219fd020360ff03030303030303030339
:100030000219fd020360ff03030303030303030329
.
.
.
.
:103fc0000219fd020360ff0303030303030303035a
:103fd0000219fd020360ff0303030303030303034a
:103fe0000219fd020360ff0303030303030303033a
:103ff0000219fd020360ff0303030303030303032a

only the memory addresses and checksum values are changing but all the data bytes are exactly the same, what is the cause of this problem with the read operation ? Is there any way to decode where exactly things are going wrong when reading the flash data from EFM8BB21 ?

![IMG_20221202_111809849](https://user-images.githubusercontent.com/25478862/205266594-db6336fd-073b-48c8-8d8d-62f5b59f1d4c.jpg)

![IMG_20221202_111454604](https://user-images.githubusercontent.com/25478862/205266559-72194876-9da1-45f4-a533-8dbb1af70d62.jpg)

These are the two variants of EFM8BB21 MCUs i am testing with, having the same issue on both 4 in 1 ESCs

**Comment by JustCurious8** [comment]
So i have confirmed that write operation is also not working properly when flashing using `python efm8.py write`. I tried flashing the bluejay firmware on a ESC MCU where it was running blheli_S firmware. This time i have all the ESCs connected with motors. But after the write operation gets completed, when i am powering the ESC then i hear blheli_S fimware startup motor tune and not the bluejay firmware motor tune.

Though, `python efm8.py write` making slight modification in the existing firmware as after running this command blhelisuite and bluejay esc configurator not able to identify the firmware on the ESC MCU which they were able to identify before. Don't know why write operation is not able to write the whole firmware, i cannot see anything going wrong with the write operation on the terminal as well.

**Comment by stylesuxx** [comment]
## Target System
* Debian Linux
* Python installed as recommended via README

### Versions
```
# python --version
Python 3.7.7

# pipenv graph
asyncio==3.4.3
pyserial==3.5
serial==0.0.97
  - future [required: >=0.17.1, installed: 0.18.2]
  - iso8601 [required: >=0.1.12, installed: 1.0.2]
  - pyyaml [required: >=3.13, installed: 6.0]
```

## Revalidate with BB51
* [x] Read with esc-configurator
* [x] Erase via C2 interface
* [x] Read via C2 interface - make sure it is erased (all 0xFF)
* [x] Make sure it is not recognized with esc-configurator
* [x] Flash latest release (0.18.1 24kHz) via C2 interface
* [x] Read with esc-configurator
* [x] Read via C2 interface (reflash.hex)
* [x] Erase via C2 interface
* [x] Read via C2 interface - make sure it is erased (all 0xFF)
* [x] Make sure it is not recognized with esc-configurator
* [x] Flash previously read hex via C2 interface
* [ ] Read with esc-configurator (Won't work because of #3)

## Revalidate with BB2
* [x] Read with esc-configurator
* [x] Erase via C2 interface
* [x] Read via C2 interface - make sure it is erased (all 0xFF)
* [x] Make sure it is not recognized with esc-configurator
* [x] Flash latest release (0.18.1 24kHz) via C2 interface
* [x] Read with esc-configurator
* [x] Read via C2 interface (reflash.hex)
* [x] Erase via C2 interface
* [x] Read via C2 interface - make sure it is erased (all 0xFF)
* [x] Make sure it is not recognized with esc-configurator
* [x] Flash previously read hex via C2 interface
* [x] Read with esc-configurator

**Comment by stylesuxx** [comment]
Closing this down: read/write/erase is now working fine with BB21.
